### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by mwmorrisCCorp** [redballoon/TM-ApplePay#1]
There is no env.js file in the repository.    The 'src directory should be renamed 'js' or vice-versa because of includes in the index.html file.

**Comment by redballoon** [comment]
Hi,
Thanks for the feedback! I added example files to the development branch to make it easy to replace the obfuscated values used for testing. Will run a test sometime tomorrow to make sure everything is still working okay before pushing to the master branch.
